[secondary_prompt]
  template = ' '
  foreground = 'p:purple'
  background = 'transparent'

[transient_prompt]
  template = ' ❯❯ {{ .AbsolutePWD }} : '
  background = 'transparent'
  foreground_templates = ['{{ if eq .Code 0 }}p:green{{ else }}p:red{{ end }}']
  newline = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = "\n╭─"
    foreground = 'p:fg'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    leading_diamond = ''
    template = '{{ .UserName }}'
    foreground = 'p:paths'
    background = 'p:bg'
    type = 'session'
    style = 'diamond'

  [[blocks.segments]]
    trailing_diamond = ''
    template = ' {{.Icon}} '
    foreground = 'p:paths'
    background = 'p:bg'
    type = 'os'
    style = 'diamond'

  [[blocks.segments]]
    leading_diamond = '<transparent,p:paths></>'
    trailing_diamond = ''
    template = ' {{ .Path }} '
    foreground = 'p:pathsFg'
    background = 'p:paths'
    type = 'path'
    style = 'diamond'
  [blocks.segments.options]
      folder_icon = '...'
      folder_separator_icon = '<transparent>  </>'
      home_icon = '󱂶 '
      style = 'agnoster_short'

      [blocks.segments.options.mapped_locations]
        '~/.config' = ' '
        '~/dotfiles' = ' '

  [[blocks.segments]]
    leading_diamond = '<transparent,background></>'
    trailing_diamond = ''
    template = '<transparent>  </> {{ reason .Code }} '
    foreground = 'p:fg'
    background = 'p:red'
    type = 'status'
    style = 'diamond'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'p:gray'
    type = 'executiontime'
    style = 'plain'
    
    [blocks.segments.options]
    style = 'round'
    threshold = 5000
[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' ({{ url .UpstreamIcon .UpstreamURL }} {{ url .HEAD .UpstreamURL }}){{ if gt .Ahead 0 }}<p:green> +{{ .Ahead }}</>{{ end }}{{ if gt .Behind 0 }}<red> -{{ .Behind }} </>{{ end }}{{ if .Working.Changed }}<p:fg>  {{ .Working.String }}</>{{ end }}{{ if .Staging.Changed }}<p:fg>  {{ .Staging.String }}</>{{ end }}'
    foreground = 'p:bg'
    background = 'p:yellow'
    type = 'git'
    style = 'diamond'
    [blocks.segments.options]
    branch_icon = ''
    cache_duration = 'none'
    display_changing_color = true
    fetch_status = true
    fetch_upstream_icon = true
    full_branch_path = true

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Full }}'
    foreground = 'p:bg'
    background = 'p:green'
    type = 'node'
    style = 'diamond'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = '󰋁 {{ .Full }}'
    foreground = 'p:bg'
    background = 'p:orange'
    type = 'pnpm'
    style = 'diamond' 
    [blocks.segments.options]
    display_mode = 'files'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Full }}'
    foreground = 'p:bg'
    background = 'p:blue'
    type = 'python'
    style = 'diamond'
    [blocks.segments.options]
    display_mode = 'files'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Full }}'
    foreground = 'p:bg'
    background = 'p:red'
    type = 'java'
    style = 'diamond'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Full }}'
    foreground = 'p:bg'
    background = 'p:blue'
    type = 'php'
    style = 'diamond'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╰─ ❯❯'
    foreground = 'p:fg'
    type = 'text'
    style = 'diamond'
