unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-Space

set -g mouse on

set -s extended-keys always
set -g terminal-features 'xtemr-ghostty:extkeys'

bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set-option -g status-position top

bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'arcticicestudio/nord-tmux'
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin 'tmux-plugins/tmux-resurrect' #persistance tmux session after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' #automatically saves the sessions every 15 minutes

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
