browsers = []
categories = []
history = false
history_when_empty = false
location = ''
set_browser_on_import = true

[Config]
hide_from_providerlist = false
icon = 'user-bookmarks'
min_score = 20
name_pretty = ''
