#name of terminal
console_title_template = '{{if .Root}} ⚡{{end}}{{.Folder | replace "~" "󱁍"}} @{{.HostName}}'
version = 4
final_space = true

# --------------------------------------------------------------------
[palette]
bg = '#1e1e2e'
fg = '#eff1f5'
paths = '#89b4fa'
pathsFg = '#11111b'
cyan = '#89dceb'
gray = '#313244'
blue = '#89b4fa'
red = '#f38ba8'
orange = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
purple = '#b4befe'
