#name of terminal
console_title_template = '{{if .Root}} ⚡{{end}}{{.Folder | replace "~" "󱁍"}} @{{.HostName}}'
version = 4
final_space = true

# --------------------------------------------------------------------
[palette]
bg = '#2E3440'
fg = '#E5E9F0'
paths = '#8FBCBB'
pathsFg = '#4C566A'
cyan = '#88C0D0'
gray = '#81A1C1'
blue = '#5E81AC'
red = '#BF616A'
orange = '#D08770'
yellow = '#EBCD8B'
green = '#A3BE8C'
purple = '#B48EAD'

