# Open cwd in a file manager
[[mgr.prepend_keymap]]
on = "o"
run = "shell 'nemo .'"
desc = "open file manager"

#maximize the preview panel
[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize the preview panel"

#exit insertmode whit jk
[[input.prepend_keymap]]
on = "<C-j>"
run = "escape"
desc = "Exit inser mode whit jk"
